image: "python:alpine"

stages:
    - build
    - test

building:
    stage: build
    script:
        - apt-get update && apt-get install -y python3-pip && pip install -r requirements.txt


testing:
    stage: test
    script:
        - python -m unittest discover -p '*_test.py'

