image: "python:alpine"

stages: 
    - build
    - test

build:
    stage: build
    script:
        - apt-get update && apt-get install -y python3-pip && pip install -r requirements.txt
            

before_script:
  - apt-get update -qq && apt-get install -y -qq sqlite3 libsqlite3-dev nodejs
  - ruby -v
  - which ruby
  - gem install bundler --no-document
  - bundle install --jobs $(nproc)  "${FLAGS[@]}"

rspec:
  script:
    - bundle exec rspec
